### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by esseremmerik** [Kyslik/view-clear#1]
I know it is just 1 day after the release, but can you please allow Laravel 5.1 to be installed so we can detect bugs or help you to improve the view-clear for 5.1? Now we cannot install laravel as composer is blocking it by your dependency setting.

Thanks.
Peter

**Comment by Kyslik** [comment]
I will look in to it, thank you.

**Comment by esseremmerik** [comment]
No problem, meanwhile we forked your project and changed the required version number in the composer file to ~5.0 and your project still works in Laravel 5.1 :)

**Comment by Kyslik** [comment]
Ok, its done; use version ~2.0.0.

Good luck.

**Comment by Kyslik** [comment]
Apparently @taylorotwell added this command to L5.1, so you do not need this package in Laravel 5.1.

Good luck.

**Comment by esseremmerik** [comment]
Ok can you point out this command from Taylorotwell to do so? As I did not find it in de documentation :-)

**Comment by Kyslik** [comment]
Just remove my package from project, do `$ composer update`, and take a look at `$ php artisan`

I did clean installl of L5.1 and view:clear command is available without this package.
